workflows:
  windows-build:
    name: Build Windows App
    instance_type: windows_x64
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build windows --release
    artifacts:
      - build/windows/runner/Release/
